apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  labels:
    db: auth-service-db
data:
  init.sql: |
    CREATE DATABASE db;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-db
  labels:
    db: auth-service-db
spec:
  selector:
    matchLabels:
      db: auth-service-db
  template:
    metadata:
      labels:
        db: auth-service-db
    spec:
      containers:
        - name: auth-service-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: admin_user
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: auth-service-config-volume
      volumes:
        - name: auth-service-config-volume
          configMap:
            name: auth-service-config

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service-db
  labels:
    db: auth-service-db
spec:
  type: ClusterIP
  selector:
    db: auth-service-db
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 5432