spring:
  application:
    name: patient-service
  profiles:
    active: development
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-service:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      username: user
      password: password
      label: master
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    bootstrap-servers: localhost:9092,localhost:9094
server:
  port: 4000
management:
  endpoints:
    web:
      exposure:
        include: refresh
patient:
  greeting: Hey patient
logging:
  level:
    root: info



