name: "config-service"

on:
  push:
    paths:
      - "config-service/**"
      - ".github/workflows/config-service.yml"
env:
  REGISTRY: ghcr.io
  SERVICE_IMAGE_NAME: oumabaros@gmail.com/analytics-service
  VERSION: latest

jobs:
  build:
    name: Build and Test analytics-service
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests
        run: |-
          cd config-service
          chmod +x mvnw
          ./mvnw install
          
